CREATE TABLE IF NOT EXISTS items (
    id          bigint   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        varchar  NOT NULL,
    description varchar  NOT NULL,
    available   boolean  NOT NULL,
    owner_id    bigint   NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    id    bigint  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar NOT NULL,
    email varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS bookings (
    id         bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_start timestamp NOT NULL,
    date_end   timestamp NOT NULL,
    item_id    bigint    NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    booker_id  bigint    NOT NULL REFERENCES users(id) ON DELETE CASCADE ,
    status     varchar   NOT NULL
);

CREATE TABlE IF NOT EXISTS comments (
    id            bigint    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text          varchar   NOT NULL,
    creation_date timestamp NOT NULL,
    item_id       bigint    NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    author_id     bigint    NOT NULL REFERENCES users(id) ON DELETE CASCADE
);